version: '3'
services:
  webserver:
    image: quay.io/astronomer/astro-runtime:12.8.0
  scheduler:
    image: quay.io/astronomer/astro-runtime:12.8.0
  triggerer:
    image: quay.io/astronomer/astro-runtime:12.8.0
  postgres:
    image: postgres:12.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
